# Generated by Django 3.1.2 on 2020-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
