# Generated by Django 3.1.2 on 2020-11-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201123_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='score',
            field=models.TextField(max_length=10),
        ),
    ]
